SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{69FB758F32C7490B}" {
   m_sName "Project Helios"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{69FB758F23051A18}" {
     m_sActionName "separator"
     m_sDisplayName "Gamemaster"
    }
    SCR_KeyBindingEntry "{69FB758EC5AEEC6C}" {
     m_sActionName "ATH_ToggleNightVision"
     m_sDisplayName "Night Vision Toggle"
     m_sPreset "click"
    }
   }
  }
 }
}