SCR_EditorActionList {
 m_Actions {
  ATH_NightVisionToolbarAction "{69FB758030F1FBB3}" {
   m_Info SCR_UIInfo "{69FB75803DB3902E}" {
    Name "NIGHT VISION"
    Icon "{890246B1CABBB073}Assets/UI/eye-svgrepo-com.edds"
   }
   m_ActionType TOGGLE
   m_ActionGroup TOOLS
   m_iOrder 4
  }
 }
}