ActionContext {
 Actions {
  Action ATH_ToggleNightVision {
   InputSource InputSourceSum "{69FB758F70D6930D}" {
    Sources {
     InputSourceValue "{69FB758F6BC4A910}" {
      Input "keyboard:KC_N"
     }
    }
   }
  }
 }
}